#include "Positions.h"

float PADDING = 5;

ImVec2 TITLEBAR_WINDOW_POS = ImVec2(0,0);
ImVec2 TITLEBAR_WINDOW_SIZE = ImVec2(1720, 20);

ImVec2 ENTITIESLIST_WINDOW_POS = ImVec2(0, 30 + PADDING); 
ImVec2 ENTITIESLIST_WINDOW_SIZE = ImVec2(460 - PADDING, 400); 

ImVec2 SIMOPTIONS_WINDOW_BG_POS = ImVec2(0, TITLEBAR_WINDOW_SIZE.y + ENTITIESLIST_WINDOW_SIZE.y + PADDING);
ImVec2 SIMOPTIONS_WINDOW_BG_SIZE = ImVec2(460 - PADDING, 1035 - SIMOPTIONS_WINDOW_BG_POS.y - PADDING);

ImVec2 USAGEANALYTICS_WINDOW_POS = ImVec2(0,0);
ImVec2 USAGEANALYTICS_WINDOW_SIZE = ImVec2(0,0);

ImVec2 ENTITYOPTIONS_WINDOW_POS = ImVec2(0,0);
ImVec2 ENTITYOPTIONS_WINDOW_SIZE = ImVec2(0,0);


