#ifndef POSITIONS_CONSTANTS_H
#define POSITIONS_CONSTANTS_H

#include <imgui.h>

extern float PADDING;

extern ImVec2 TITLEBAR_WINDOW_POS;
extern ImVec2 TITLEBAR_WINDOW_SIZE;

extern ImVec2 ENTITIESLIST_WINDOW_POS; 
extern ImVec2 ENTITIESLIST_WINDOW_SIZE; 

extern ImVec2 SIMOPTIONS_WINDOW_BG_POS;
extern ImVec2 SIMOPTIONS_WINDOW_BG_SIZE;

extern ImVec2 USAGEANALYTICS_WINDOW_POS;
extern ImVec2 USAGEANALYTICS_WINDOW_SIZE;

extern ImVec2 ENTITYOPTIONS_WINDOW_POS;
extern ImVec2 ENTITYOPTIONS_WINDOW_SIZE;

#endif
